# .github/workflows/notify-deadlines.yml
name: "Notify Deadlines"

# 毎日 23:00 (UTC) に実行、かつ手動トリガーも可
on:
  schedule:
    - cron: "0 23 * * *"     # 毎日 23:00 UTC → 翌日 8:00 JST
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call notify-deadlines endpoint
        # VERCEL_BASE_URL というリポジトリシークレットに
        # https://kanban-app-yops.vercel.app を登録しておく
        env:
          BASE_URL: ${{ secrets.VERCEL_BASE_URL }}
        run: |
          echo "▶︎ Calling ${BASE_URL}/api/tasks/notify-deadlines"
          curl -fSL "${BASE_URL}/api/tasks/notify-deadlines?today=$(date +%Y-%m-%d)" \
            -H "Accept: application/json"
